ARG BASE_IMAGE=nvcr.io/nvidia/cuda:12.5.1-devel-ubuntu20.04
ARG ssh_prv_key
ARG ssh_pub_key
FROM ${BASE_IMAGE}

RUN echo "root:8uhb9ijn" | chpasswd
EXPOSE 22

ARG APPS_PATH=/opt/apps
ARG CODE_PATH=${APPS_PATH}/code
ARG VENV_PATH=${APPS_PATH}/venv
ARG http_proxy
ARG ftp_proxy
ARG https_proxy
ENV http_proxy=${http_proxy}
ENV https_proxy=${http_proxy}
ENV ftp_proxy=${http_proxy}
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y --no-install-recommends update && \
    apt install -y --no-install-recommends apt-utils && \
    apt-get -y --no-install-recommends install \
    wget \
    git bash-completion \
    clang lld ninja-build ccache libssl-dev clang-format \
    vim \
    build-essential \
    python3-dev python3-pip python3-venv \
    sudo \
    iputils-ping \
    net-tools \
    openssh-client \
    openssh-server \
    gdb \
    tree \
    # install python env
    build-essential \
    zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev \
    libssl-dev libreadline-dev libffi-dev libsqlite3-dev \
    libbz2-dev liblzma-dev uuid-dev xz-utils tk-dev curl ca-certificates \
    > /dev/null && \
    apt-get clean && apt-get purge && rm -rf /var/lib/apt/lists && \
    echo "if [ -f /etc/bash_completion.d/git ]; then\n\
    . /etc/bash_completion.d/git\n\
fi\n\
" >> /etc/profile
# config language
ENV LANG=C.UTF-8
# install python 
RUN mkdir /tmp/python && cd /tmp/python && \
    wget https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tgz && \
    tar -xzf Python-3.11.2.tgz && cd Python-3.11.2 && \
    ./configure --with-pydebug --enable-optimizations --with-ensurepip=install && \
    make -j$(nproc) && make altinstall && \
    cd .. && rm -rf /tmp/python && \
    ln -sf /usr/local/bin/python3.11 /usr/local/bin/python && \
    ln -sf /usr/local/bin/python3.11 /usr/local/bin/python3 && \
    ln -sf /usr/local/bin/python3.11 /usr/bin/python3 && \
    ln -sf /usr/local/bin/pip3.11 /usr/local/bin/pip && \
    ln -sf /usr/local/bin/pip3.11 /usr/local/bin/pip3

# 设置sshd自启动
# RUN mkdir -p /var/run/sshd
# CMD ["/usr/sbin/sshd", "-D"]
ENTRYPOINT service ssh restart && bash
WORKDIR /host
# ENTRYPOINT ["/bin/bash"]
